Add Tests (#2)
* wip

* wip

* wip

* wip

* wip

* wip

* wip

* wip

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -12,12 +12,16 @@ outputs:
 runs:
   using: "composite"
   steps:
+    - name: Check ref
+      shell: bash
+      run: |
+        if [[ "${{ github.ref }}" != "refs/tags/"* ]]; then
+          echo "::error::Not a tag ref ${{ github.ref }}"
+          exit 1
+        fi
+
     - name: Determine tag
       id: get-tag
       shell: bash
-      run: |
-        # Strip git ref prefix from version
-        TAG=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
-        # Strip "v" prefix from tag name
-        [[ "${{ github.ref }}" == "refs/tags/"* ]] && TAG=$(echo $TAG | sed -e 's/^v//')
-        echo "::set-output name=tag::$TAG"
+      run: echo "::set-output name=tag::$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')"
+
